import type { Venue, Booking } from "../lib/types"

// Mock Venues Data
export const venues: Venue[] = [
  {
    id: "venue-1",
    name: "Modern Downtown Loft",
    description: "A spacious loft in the heart of downtown, perfect for corporate events and photoshoots.",
    location: "Downtown, New York",
    pricePerHour: 150,
    capacity: 50,
    amenities: ["WiFi", "Kitchen", "AV Equipment", "Parking", "Wheelchair Access"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.8,
    reviewCount: 124,
    featured: true,
  },
  {
    id: "venue-2",
    name: "Elegant Ballroom",
    description: "A luxurious ballroom with high ceilings and chandeliers, ideal for weddings and galas.",
    location: "Midtown, Chicago",
    pricePerHour: 300,
    capacity: 200,
    amenities: ["WiFi", "Kitchen", "AV Equipment", "Parking", "Wheelchair Access"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.9,
    reviewCount: 87,
    featured: true,
  },
  {
    id: "venue-3",
    name: "Rustic Barn Venue",
    description: "A charming barn venue with rustic decor, perfect for weddings and country-themed events.",
    location: "Countryside, Austin",
    pricePerHour: 200,
    capacity: 150,
    amenities: ["WiFi", "Kitchen", "Parking"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "venue-4",
    name: "Rooftop Garden",
    description:
      "A beautiful rooftop garden with panoramic city views, perfect for cocktail parties and small gatherings.",
    location: "Downtown, Los Angeles",
    pricePerHour: 250,
    capacity: 80,
    amenities: ["WiFi", "Bar", "Parking"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.6,
    reviewCount: 42,
  },
  {
    id: "venue-5",
    name: "Industrial Warehouse",
    description: "A converted warehouse with industrial charm, ideal for art exhibitions and fashion shows.",
    location: "Brooklyn, New York",
    pricePerHour: 180,
    capacity: 120,
    amenities: ["WiFi", "AV Equipment", "Parking"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.5,
    reviewCount: 38,
  },
  {
    id: "venue-6",
    name: "Beachfront Villa",
    description: "A stunning beachfront villa with ocean views, perfect for intimate weddings and private parties.",
    location: "Malibu, California",
    pricePerHour: 400,
    capacity: 60,
    amenities: ["WiFi", "Kitchen", "Pool", "Parking"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.9,
    reviewCount: 29,
    featured: true,
  },
  {
    id: "venue-7",
    name: "Conference Center",
    description:
      "A professional conference center with state-of-the-art facilities, ideal for business meetings and seminars.",
    location: "Financial District, San Francisco",
    pricePerHour: 220,
    capacity: 100,
    amenities: ["WiFi", "AV Equipment", "Catering", "Parking", "Wheelchair Access"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.7,
    reviewCount: 63,
  },
  {
    id: "venue-8",
    name: "Art Gallery Space",
    description:
      "A minimalist art gallery with white walls and high ceilings, perfect for exhibitions and creative events.",
    location: "SoHo, New York",
    pricePerHour: 170,
    capacity: 70,
    amenities: ["WiFi", "AV Equipment", "Wheelchair Access"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.6,
    reviewCount: 45,
  },
  {
    id: "venue-9",
    name: "Historic Mansion",
    description: "A grand historic mansion with elegant interiors, ideal for upscale events and period-themed parties.",
    location: "Georgetown, Washington DC",
    pricePerHour: 350,
    capacity: 120,
    amenities: ["WiFi", "Kitchen", "Garden", "Parking"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.8,
    reviewCount: 52,
  },
  {
    id: "venue-10",
    name: "Cozy Studio Space",
    description: "A intimate studio space perfect for workshops, small gatherings, and photo shoots.",
    location: "Williamsburg, Brooklyn",
    pricePerHour: 100,
    capacity: 30,
    amenities: ["WiFi", "Natural Light", "AV Equipment"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.5,
    reviewCount: 37,
  },
  {
    id: "venue-11",
    name: "Luxury Yacht",
    description: "A stunning yacht for exclusive events on the water, offering a unique and memorable experience.",
    location: "Marina, Miami",
    pricePerHour: 500,
    capacity: 40,
    amenities: ["WiFi", "Bar", "Sound System", "Catering"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.9,
    reviewCount: 23,
    featured: true,
  },
  {
    id: "venue-12",
    name: "Mountain Lodge",
    description: "A rustic mountain lodge with breathtaking views, perfect for retreats and team-building events.",
    location: "Aspen, Colorado",
    pricePerHour: 280,
    capacity: 80,
    amenities: ["WiFi", "Kitchen", "Fireplace", "Parking"],
    images: ["/placeholder.svg?height=400&width=600"],
    rating: 4.7,
    reviewCount: 41,
  },
]

// Mock Bookings Data
export const bookings: Booking[] = [
  {
    id: "booking-1",
    venueId: "venue-1",
    userId: "user-1",
    date: "2023-06-15",
    startTime: "14:00",
    endTime: "18:00",
    guests: 30,
    status: "confirmed",
    totalPrice: 600,
    notes: "Corporate team building event",
    createdAt: "2023-05-20T10:30:00Z",
  },
  {
    id: "booking-2",
    venueId: "venue-2",
    userId: "user-2",
    date: "2023-07-22",
    startTime: "16:00",
    endTime: "22:00",
    guests: 150,
    status: "confirmed",
    totalPrice: 1800,
    notes: "Wedding reception",
    createdAt: "2023-05-15T14:45:00Z",
  },
  {
    id: "booking-3",
    venueId: "venue-3",
    userId: "user-3",
    date: "2023-06-10",
    startTime: "12:00",
    endTime: "16:00",
    guests: 80,
    status: "pending",
    totalPrice: 800,
    notes: "Birthday celebration",
    createdAt: "2023-05-25T09:15:00Z",
  },
]
